# Site settings
title: Tao Peng
# email: pt@taopeng.me
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on programming, hacking, technology and maps.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.taopeng.me" # the base hostname & protocol for your site
twitter_username: ptpt
github_username:  ptpt
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
